PREFIX: '&x&0&8&4&c&f&b[&x&1&2&5&6&f&bV&x&1&b&6&0&f&ba&x&2&5&6&9&f&bs&x&2&f&7&3&f&bi&x&3&9&7&d&f&cl&x&4&2&8&7&f&ci&x&4&c&9&1&f&ct&x&5&6&9&b&f&cy&x&5&f&a&4&f&cE&x&6&9&a&e&f&cn&x&7&3&b&8&f&cc&x&7&c&c&2&f&ch&x&8&6&c&c&f&da&x&9&0&d&6&f&dn&x&9&a&d&f&f&dt&x&a&3&e&9&f&ds&x&a&d&f&3&f&d] &r'
GUIName: '&aVasilityEnchants'

MaxLevelOutput: '&c&lMAX' # %level% output if item reached the last level

BookItem:
  Name: '%enchantment%'
  Lore:
    - '&f'
    - '&aPrice: %price%'
    - '&aNext Level: %level%'
    - '&f'
    - '&aClick to enchant!'

HELMET:
  AQUA_AFFINITY:
    1: 100
    2: 200
    3: 300
    4: 400
    5: 500
  BLAST_PROTECTION:
    1: 100
    2: 200
    3: 300
    4: 400
    5: 500
  FIRE_PROTECTION:
    1: 100
    2: 200
    3: 300
    4: 400
    5: 500
  PROJECTILE_PROTECTION:
    1: 100
    2: 200
    3: 300
    4: 400
    5: 500
  PROTECTION:
    1: 100
    2: 200
    3: 300
    4: 400
    5: 500
  RESPIRATION:
    1: 100
    2: 200
    3: 300
    4: 400
    5: 500
  THORNS:
    1: 100
    2: 200
    3: 300
    4: 400
    5: 500
  UNBREAKING:
    1: 100
    2: 200
    3: 300
    4: 400
    5: 500
  MENDING:
    1: 10000
  BINDING_CURSE:
    1: 10000
  VANISHING_CURSE:
    1: 10000